---
title: 'Histogramas: Proyecto Diseño Experimental'
author: "Arenas Tamara, Medina Nuria, Noriega Berenice, Picasso David, Ruiz Braulio, Vázquez Mariana"
date:  "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#HISTOGRAMAS EN FUNCIÓN DE QUÉ TAN GRACIOSO FUERON LOS CHISTES

#Cargando librerías y base de datos
```{r Librerias_datos, message=FALSE, warning=FALSE, include=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, ggpubr, coin, effsize,PMCMRplus)
BD <- read.csv(file = "../Output/BD.csv")
```

#Obtenemos descriptivos
Esto nos permitirá calcular las medidas de estadística descriptiva.

```{r Descriptivos_chiste_tot, echo=TRUE, message=FALSE, warning=FALSE}
BD %>% group_by(Sexo_Aplicador) %>% summarise(
  media= mean(ChGtot),
  mediana= median(ChGtot),
  ds= sd(ChGtot),
  varianza= var(ChGtot),
  minimo= min(ChGtot),
  maximo= max(ChGtot),
  muestra= n(),
  error_estandar=ds/sqrt(muestra),
  i_confianza_low= media-2*error_estandar,
  i_confianza_up= media+2*error_estandar
)
```

#Generar histograma por chiste (qué tan gracioso fue)

#Chiste 1
```{r Chiste1, echo=TRUE, message=FALSE, warning=FALSE}
ggplot(BD, aes(x = ChG1, color = Sexo_Aplicador, fill = Sexo_Aplicador)) +
  geom_histogram(alpha=0.5)+
  scale_color_manual(values = c("#AD84BC","#E97979"))+
  scale_fill_manual(values = c("#AD84BC","#E97979"))+
  theme_classic()+
  labs(x = 'Nivel de comicidad del chiste 1',
       y = 'Frecuencia') +
  theme(legend.position = "none")
```
#Chiste 2
```{r Chiste2, echo=TRUE, message=FALSE, warning=FALSE}
ggplot(BD, aes(x = ChG2, color = Sexo_Aplicador, fill = Sexo_Aplicador)) +
  geom_histogram(alpha=0.5)+
  scale_color_manual(values = c("#AD84BC","#E97979"))+
  scale_fill_manual(values = c("#AD84BC","#E97979"))+
  theme_classic()+
  labs(x = 'Nivel de comicidad del chiste 2',
       y = 'Frecuencia') +
  theme(legend.position = "none")
```

#Chiste 3
```{r Chiste3, echo=TRUE, message=FALSE, warning=FALSE}
ggplot(BD, aes(x = ChG3, color = Sexo_Aplicador, fill = Sexo_Aplicador)) +
  geom_histogram(alpha=0.5)+
  scale_color_manual(values = c("#AD84BC","#E97979"))+
  scale_fill_manual(values = c("#AD84BC","#E97979"))+
  theme_classic()+
  labs(x = 'Nivel de comicidad del chiste 3',
       y = 'Frecuencia') +
  theme(legend.position = "none")
```

#Chiste 4
```{r Chiste4, echo=TRUE, message=FALSE, warning=FALSE}
ggplot(BD, aes(x = ChG4, color = Sexo_Aplicador, fill = Sexo_Aplicador)) +
  geom_histogram(alpha=0.5)+
  scale_color_manual(values = c("#AD84BC","#E97979"))+
  scale_fill_manual(values = c("#AD84BC","#E97979"))+
  theme_classic()+
  labs(x = 'Nivel de comicidad del chiste 4',
       y = 'Frecuencia') +
  theme(legend.position = "none")
```

#Chiste 5
```{r Chiste5, echo=TRUE, message=FALSE, warning=FALSE}
ggplot(BD, aes(x = ChG5, color = Sexo_Aplicador, fill = Sexo_Aplicador)) +
  geom_histogram(alpha=0.5)+
  scale_color_manual(values = c("#AD84BC","#E97979"))+
  scale_fill_manual(values = c("#AD84BC","#E97979"))+
  theme_classic()+
  labs(x = 'Nivel de comicidad del chiste 5',
       y = 'Frecuencia') +
  theme(legend.position = "none")
```

#Chiste total
```{r Chistetot, echo=TRUE, message=FALSE, warning=FALSE}
ggplot(BD, aes(x = ChGtot, color = Sexo_Aplicador, fill = Sexo_Aplicador)) +
  geom_histogram(alpha=0.5)+
  scale_color_manual(values = c("#AD84BC","#E97979"))+
  scale_fill_manual(values = c("#AD84BC","#E97979"))+
  theme_classic()+
  labs(x = 'Nivel de comicidad del todos los chistes',
       y = 'Frecuencia') +
  theme(legend.position = "none")
```